##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-system-monitor
    - gcc
    - git
    - gtkmm3
    - intltool
    - libgtop
    - libwnck3
    - make
    - mate-common
    - mate-desktop
    - which
    - yelp-tools

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-system-monitor
    - g++
    - git
    - intltool
    - libglib2.0-dev
    - libglibmm-2.4-dev
    - libgtk-3-dev
    - libgtkmm-3.0-dev
    - libgtop2-dev
    - librsvg2-dev
    - libsystemd-dev
    - libwnck-3-dev
    - libxml2-dev
    - make
    - mate-common
    - quilt
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-system-monitor.git
    - gcc
    - gcc-c++
    - dbus-glib-devel
    - desktop-file-utils
    - git
    - gtk3-devel
    - gtkmm30-devel
    - libgtop2-devel
    - librsvg2-devel
    - libwnck3-devel
    - libxml2-devel
    - make
    - mate-common
    - redhat-rpm-config
    - systemd-devel

  ubuntu:
    - g++
    - git
    - intltool
    - libglib2.0-dev
    - libglibmm-2.4-dev
    - libgtk-3-dev
    - libgtkmm-3.0-dev
    - libgtop2-dev
    - librsvg2-dev
    - libsystemd-dev
    - libwnck-3-dev
    - libxml2-dev
    - make
    - mate-common
    - quilt
    - yelp-tools

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-system-monitor-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
